global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'prometheus-stack-monitor'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "batch_job_rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'push-gateway'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['push-gateway:9091']

  - job_name: "spark-app"
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['spark-app:9999']

  - job_name: "cadvisor"
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['cadvisor:8080']